header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Alessandro De Blasis <alex@deblasis.net>  

  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'

  comment: on-failure

  dependency:
  files:
    - go.mod