# The MIT License (MIT)
#
# Copyright (c) 2021 Alessandro De Blasis <alex@deblasis.net>  
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE. 
#
version: '3.6'

services:

  apigateway:
    build:
      dockerfile: ./services/apigateway/Dockerfile.hostbuild
      context: .
      args: 
        SVC_NAME: apigateway

  auth_dbsvc:
    build:
      dockerfile: ./services/auth_dbsvc/Dockerfile.hostbuild
      context: .
      args: 
        SVC_NAME: auth_dbsvc
   
  authsvc:
    build:
      dockerfile: ./services/authsvc/Dockerfile.hostbuild
      context: .
      args: 
        SVC_NAME: authsvc
   
  centralcommand_dbsvc:
    build:
      dockerfile: ./services/centralcommand_dbsvc/Dockerfile.hostbuild
      context: .
      args: 
        SVC_NAME: centralcommand_dbsvc

  centralcommandsvc:
    build:
      dockerfile: ./services/centralcommandsvc/Dockerfile.hostbuild
      context: .
      args: 
        SVC_NAME: centralcommandsvc

  shippingstationsvc:
    build:
      dockerfile: ./services/shippingstationsvc/Dockerfile.hostbuild
      context: .
      args: 
        SVC_NAME: shippingstationsvc

  clessidrasvc:
    build:
      dockerfile: ./services/clessidrasvc/Dockerfile.hostbuild
      context: .
      args: 
        SVC_NAME: clessidrasvc        
   
  integrationtester:
    build:
      dockerfile: ./e2e_tests/docker/Dockerfile
      context: .
      args: 
        SVC_NAME: integrationtester        
      