#
# Copyright 2021 Alessandro De Blasis <alex@deblasis.net>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
version: '3.6'

services:

  apigateway:
    build:
      dockerfile: ./services/apigateway/Dockerfile.hostbuild
      context: .
      args: 
        SVC_NAME: apigateway

  auth_dbsvc:
    build:
      dockerfile: ./services/auth_dbsvc/Dockerfile.hostbuild
      context: .
      args: 
        SVC_NAME: auth_dbsvc
   
  authsvc:
    build:
      dockerfile: ./services/authsvc/Dockerfile.hostbuild
      context: .
      args: 
        SVC_NAME: authsvc
   
  centralcommand_dbsvc:
    build:
      dockerfile: ./services/centralcommand_dbsvc/Dockerfile.hostbuild
      context: .
      args: 
        SVC_NAME: centralcommand_dbsvc

  centralcommandsvc:
    build:
      dockerfile: ./services/centralcommandsvc/Dockerfile.hostbuild
      context: .
      args: 
        SVC_NAME: centralcommandsvc

  shippingstationsvc:
    build:
      dockerfile: ./services/shippingstationsvc/Dockerfile.hostbuild
      context: .
      args: 
        SVC_NAME: shippingstationsvc

  clessidrasvc:
    build:
      dockerfile: ./services/clessidrasvc/Dockerfile.hostbuild
      context: .
      args: 
        SVC_NAME: clessidrasvc        
   