version: '3'

services:

  # apigateway:
  #   build:
  #     dockerfile: ./services/apigateway/Dockerfile
  #     context: .
  #     args: 
  #       SVC_NAME: apigateway
  #   ports:
  #     - 8081:8081
  #     - 8082:8082
  #   depends_on: 
  #     - consul
  #     - authsvc
  #   volumes:
  #     - ./certs:/certs
  #     - ./services/apigateway/app.yaml:/app.yaml
  #   environment: 
  #    DEBLASIS_BINDONLOCALHOST: "false"
  #    DEBLASIS_SSL_SERVERCERT: /certs/deblasis-stc.pem
  #    DEBLASIS_SSL_SERVERKEY: /certs/deblasis-stc-key.pem
  #   networks:
  #     - net      
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3


  auth_dbsvc:
    build:
      dockerfile: ./services/auth_dbsvc/Dockerfile
      context: .
      args: 
        SVC_NAME: auth_dbsvc

  centralcommand_dbsvc:
    build:
      dockerfile: ./services/centralcommand_dbsvc/Dockerfile
      context: .
      args: 
        SVC_NAME: centralcommand_dbsvc
   
  authsvc:
    build:
      dockerfile: ./services/authsvc/Dockerfile
      context: .
      args: 
        SVC_NAME: authsvc
   
  centralcommandsvc:
    build:
      dockerfile: ./services/centralcommandsvc/Dockerfile
      context: .
      args: 
        SVC_NAME: centralcommandsvc
   