httpserverport: 8081
grpcserverport: 8082

db:
  address: centralcommand_db:5432
  username: postgres
  password: secret
  database: centralcommand
  sslmode: disable
  drivername: postgres


loglevel: debug