@baseUrl = http://localhost:8081

//HEALTH
GET {{baseUrl}}/health HTTP/1.1

###

//CreateUser KO
POST {{baseUrl}}/user/signup HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "username": "asdaafvguaw4a",
    "password": "asddaeawea",
    "role": "Ship"
}

###

//Login
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "username": "deblasis",
    "password": "password!"
}

###

//RegisterStation
POST {{baseUrl}}/centcom/station/register HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTMxZmZlMTItMWQxNC00Y2M1LWE2YmYtZTk5MDJhYjdhMzAyIiwidXNlcm5hbWUiOiJzdGFhYWFhdCIsInJvbGUiOiJTdGF0aW9uIiwiYXVkIjoiZGVibGFzaXMuU3BhY2VUcmFmZmljQ29udHJvbCIsImV4cCI6MTYzMTkxMTMzMSwianRpIjoiNDRlYzQ3NTUtYjFhMy00YjYzLWIxZjctNDg0OTZmYTljODQxIiwiaWF0IjoxNjMxODI0OTMxLCJpc3MiOiJodHRwOi8vZGVibGFzaXMtdjEtQXV0aFNlcnZpY2UifQ.LKSBKwdpKBWkMZKaOzLeUBbgG0vTi4LwmYImIagve65TIgSkvb4ASLATQY3S3zA1yoMhwI_Fk3zogqlWSLEQhqXAG_eBMLayWqBK3U7ZekcOEc96t3rARB-UwnnKhXsvdWKh4yNuiebmQWkfjpMunKD3Hi6BCP96DGeFeABewXA3UjBfKWsG0aTEMzxfwXslLgjIXoRa1WYsmFA41gp-FPZj6S7_GOg8fnd4GskFeJ0e7NbZVSlImGnep8tNDLvcf8JDBX6Eqqqn4EhNvUnUZr_m2a4STCTdZp3Ae-t1p6SPVQYBaYL47NmRNNYcOY6v1V2iC8a_ZWs5p3Y2YVNrZw

{
   "capacity":"2342.4234",
   "docks":[
      {
         "numDockingPorts":"15"
      }
   ]
}
###
GET {{baseUrl}}/centcom/station/all HTTP/1.1
Content-Type: application/json; charset=utf-8
#Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImRlYmxhc2lzIiwicm9sZSI6IkNvbW1hbmQiLCJhdWQiOiJkZWJsYXNpcy5TcGFjZVRyYWZmaWNDb250cm9sIiwiZXhwIjoxNjMxNzIwNDMxLCJqdGkiOiJlZTFmZjhmMS1lNzA2LTQwNDMtYTAxMC04OGFlOTExMjZhMmQiLCJpYXQiOjE2MzE2MzQwMzEsImlzcyI6ImRlYmxhc2lzLnYxLkF1dGhTZXJ2aWNlIn0.t9ysGgvBsMqpO3O4qrmAI2quer4f1H4kzj1iRYaXFnz8CrL1HrFhqj5HhKTUgz8K4wHQ7-4Wgtk4qb3uJ4G3N0v1YeYIdjDssal0HCXC7HnnrBp60IAGoZKsuOyI6r2TziKs8tO8oMhx6u1fDiGzO9krYfUSgie9ERtfZroxBlFSimOkB0UJ0Q5O5rMRuQ0hSa3VDQO57g5QVlkdSkXS8uzqvc4HuB-aoI4w1ZtUG-4jFIFZmV8GOeIdi9tR2EpQ9dZPNU-RcDOZolDBjI6ewx6O46e4kmgs_qdDZ3tiAJsp1MC4q6bm3iFsHxk_g8nQwmFoq8_kJ2u8GA2b0wGg_g


###
GET {{baseUrl}}/centcom/ship/all HTTP/1.1
Content-Type: application/json; charset=utf-8
#Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImRlYmxhc2lzIiwicm9sZSI6IkNvbW1hbmQiLCJhdWQiOiJkZWJsYXNpcy5TcGFjZVRyYWZmaWNDb250cm9sIiwiZXhwIjoxNjMxNzIwNDMxLCJqdGkiOiJlZTFmZjhmMS1lNzA2LTQwNDMtYTAxMC04OGFlOTExMjZhMmQiLCJpYXQiOjE2MzE2MzQwMzEsImlzcyI6ImRlYmxhc2lzLnYxLkF1dGhTZXJ2aWNlIn0.t9ysGgvBsMqpO3O4qrmAI2quer4f1H4kzj1iRYaXFnz8CrL1HrFhqj5HhKTUgz8K4wHQ7-4Wgtk4qb3uJ4G3N0v1YeYIdjDssal0HCXC7HnnrBp60IAGoZKsuOyI6r2TziKs8tO8oMhx6u1fDiGzO9krYfUSgie9ERtfZroxBlFSimOkB0UJ0Q5O5rMRuQ0hSa3VDQO57g5QVlkdSkXS8uzqvc4HuB-aoI4w1ZtUG-4jFIFZmV8GOeIdi9tR2EpQ9dZPNU-RcDOZolDBjI6ewx6O46e4kmgs_qdDZ3tiAJsp1MC4q6bm3iFsHxk_g8nQwmFoq8_kJ2u8GA2b0wGg_g

###

//RegisterShip
POST {{baseUrl}}/centcom/ship/register HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTM4NzFmNWQtODM4My00MjI3LTg2ZjItNDhhNWFhZTVkYmZiIiwidXNlcm5hbWUiOiJzdGFhYWF0Iiwicm9sZSI6IlNoaXAiLCJhdWQiOiJkZWJsYXNpcy5TcGFjZVRyYWZmaWNDb250cm9sIiwiZXhwIjoxNjMxOTExMDc1LCJqdGkiOiJiZGNmZTcwMi1lNGM3LTRhYTUtOWFiZi1mODYwODEwMjQ5ZDUiLCJpYXQiOjE2MzE4MjQ2NzUsImlzcyI6Imh0dHA6Ly9kZWJsYXNpcy12MS1BdXRoU2VydmljZSJ9.K-UKokVzxBjRAIE9q_FGZBDzNK_0kumTyFoce3GkKzTNtcvg9nH00Q-z4fwDS1jsD_H7w9CSLWAOQm6upjIyw_2q1KVt8UML1526dfpK6KNT8W88LMM1VNmEiPW4qB8LyWQdpUntRJ5K9KRP9Ov_qeCuwGUM53jmZTU3shohVxmZH7AFY0czyWBW8igNlAphX-MmUrclLrvvBlF1BkVZxyNSpJTlf_v8ORDr-eXf7GX4QMPcpHklOjCD4nwGRgn4qxgOIHI6TmBbZZDq3-hVgoKKqMGsJwLHUkUvUhMCNmVvV8iTXxIUKZvLxyiKMrn_A_C9Z8zmKmvfkGYTl7pyCg

{
   "weight": 124123.52
}


# grpcurl -import-path ./services/auth_dbsvc/pb/ -proto auth_dbsvc.proto -d @ -plaintext localhost:8082 AuthDBSvc/CreateUser <<EOM                                                                             baremetal-cluster 
# {
#   "user": {
#     "username": "He6a6rl86757r8a4ltto",
#     "password": "Hello",
#     "role": "COMMAND"
#   }
# }
# EOM