@baseUrl = http://localhost:8081

//HEALTH
GET {{baseUrl}}/health HTTP/1.1

###

//CreateUser KO
POST {{baseUrl}}/user/signup HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNmZlNGVkYTUtMTEyMS00NDkxLWExYjQtOTU4ZTczNjE3NzU2IiwidXNlcm5hbWUiOiJkZWJsYXNpcyIsInJvbGUiOiJDb21tYW5kIiwiYXVkIjoiZGVibGFzaXMuU3BhY2VUcmFmZmljQ29udHJvbCIsImV4cCI6MTYzMjc3OTQxOSwianRpIjoiNzg1ZjE1NGUtZjZjMC00N2FmLThiNGYtYTUxMjgwMWY5ZGM2IiwiaWF0IjoxNjMyNjkzMDE5LCJpc3MiOiJodHRwOi8vZGVibGFzaXMtdjEtQXV0aFNlcnZpY2UifQ.cqS_9zuVbpr9-5dkA1C5aQUJmGcnfbPtEJA_wWzEUsvklbC-WR50kmxVu96EW7eA2KvJibyKcvIE1yEN2ZnVIH5_YOsze4hYTlLr6OLcnQ-rQu0Y7q3xUsb0R0Bnntu4LIhd1M74zGsAiztXmTydvIjfu6xjlBx9fMCl0j38GufSXc4ShEckdsATqoNYxuX4wK_VvEDSeb_QBgqjNVBtb6WzcwSccreoxn1hK7CV9xv1D8Iuu91jVWZOCGZa1Tc_7eKLC_0KaLrBbr91N_0dJhI1_2Vai6vvRoSvC-7SMqwctjxW17Tpi20H2hb_9oZLgehgV7tzH9wzZhE1tzBWAw
Content-Type: application/json; charset=utf-8

{
    "username": "asdasaasddaaafvagaasuaw4a",
    "password": "asddaeawea",
    "role": "Station"
}

###

//Login
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "username": "deblasis",
    "password": "password!"
}

###

//Login
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "username": "Persona_Ship_MilleniumFalcon",
    "password": "Persona_Ship_MilleniumFalcon"
}

###

//RegisterStation
POST {{baseUrl}}/centcom/station/register HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZWM5NzUwNzQtYjg0Zi00Y2VlLWE5OWUtMzJlZWE5MzViMjhkIiwidXNlcm5hbWUiOiJhc2Rhc2Fhc2RkYWFhZnZhZ2Fhc3VhdzRhIiwicm9sZSI6IlN0YXRpb24iLCJhdWQiOiJkZWJsYXNpcy5TcGFjZVRyYWZmaWNDb250cm9sIiwiZXhwIjoxNjMyNzc5NDMyLCJqdGkiOiJiM2U3MzRiYS1iOTQ5LTRjNjEtOTg1ZC0yMzhmMzJlYTdlYTUiLCJpYXQiOjE2MzI2OTMwMzIsImlzcyI6Imh0dHA6Ly9kZWJsYXNpcy12MS1BdXRoU2VydmljZSJ9.AxI7pNM5S6zdeYICNri8gH3UtvNKMXLjk5eqnBq2BnKMCeiKrOKQu_eqPusHk2Mk9F4CKfX_9gnQxl1c1fql8q4Cxsuv7oe1h7CRt349BVSr_X-KP0nahuisKVrqTKfeIWBdsapWP3Ud8_hw_NUrJumgLqMWKBM_uwwvdIuvXmJfFedGTFVPaj1RUSNW5-G9Mv_GYsb_TOwwc8496X3SJUUVHvZCaWj4E815mBF32WBREAeqVnc9D7jil87nztAzU0zWJOJq8ZgsenT2Jqi_pQE-6wdnnXd_OeD1IvE86nhzMP1uE4BnFvh5PyG01OANbGBptloX9ac4LWSxnZBYtA

{
   "capacity":"2342.4234"
}
###
GET {{baseUrl}}/centcom/station/all HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiM2FmM2M2YWYtNzFlYS00M2ZjLWE4YmEtM2ZiZmJmYTI1OGMyIiwidXNlcm5hbWUiOiJkZWJsYXNpcyIsInJvbGUiOiJDb21tYW5kIiwiYXVkIjoiZGVibGFzaXMuU3BhY2VUcmFmZmljQ29udHJvbCIsImV4cCI6MTYzMjQ3NTkxMiwianRpIjoiY2U2M2Y0YjYtYjQyOC00OTAyLTg4NjktZTRjODEyZDRjZWQzIiwiaWF0IjoxNjMyMzg5NTEyLCJpc3MiOiJodHRwOi8vZGVibGFzaXMtdjEtQXV0aFNlcnZpY2UifQ.BRbtONJFWN5Tb4cmQvGoAGB3cKpXYj85Z0eTGNhw7TTlbGdzkyY2LjLwoLytztoLkMdEb3-5TIVjpV2uaXKPK6L9xFEOKoOFrvwqSRprDSUVnipY8w4RpR6fkcx8NTEdSwcokgcsRac88oOAW5t89IUiu__c9K10vKomUOWMxRbfMbGsy94QYjtTeOsZiDxSJAmISY-abQMUhjeD5SKMCF_bCUmzyZTtgYkM7x0dZ1rS9G99fFpJEhJy0vYcL1fMVFHGK16xJcEJuArYCzDxMa7g3PlB-BgV-Lme7c3BOZX4WSVA6p3bRvo4Ux2G5-GlwnRqJil8SKy3eAS3VFGrRA


###
GET {{baseUrl}}/centcom/ship/all HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiM2FmM2M2YWYtNzFlYS00M2ZjLWE4YmEtM2ZiZmJmYTI1OGMyIiwidXNlcm5hbWUiOiJkZWJsYXNpcyIsInJvbGUiOiJDb21tYW5kIiwiYXVkIjoiZGVibGFzaXMuU3BhY2VUcmFmZmljQ29udHJvbCIsImV4cCI6MTYzMjQ4OTU2NiwianRpIjoiODA2ZWQzZDctOGU4Zi00NDI0LWExMjctZDY3N2ZkODIyYTRjIiwiaWF0IjoxNjMyNDAzMTY2LCJpc3MiOiJodHRwOi8vZGVibGFzaXMtdjEtQXV0aFNlcnZpY2UifQ.RPVOL13wvSXI0YDp32wVAd3wyho1-dufcEMWDdQGu7iIxmPslkXMqBpP76HnQtjBG5R1oDYqU_FsmqznTs41Syiajfw04ZG6FqtYV0AMSkC4B1zrinCp3MOKtjfAYYhtXMM9Bt6eWvbwYEsBAAbdPUU6nIasFchSuo45wlA1Gwrc9R0uciDupRJao1Dm5f3s-URMY4oZQtypHcrbyqApHPv7ARvelLswOjcGdinHHppZXiW1uHFQV97oXULTJk6v7-M64fKfru6FZ9elEEviZnbJyPmwJJEiZg10648q-pOVJXBQMIiOWiFgCpdoLb5QWfGDS1DDf4782Ev8-e6RxA

###

//RegisterShip
POST {{baseUrl}}/centcom/ship/register HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTdiZDBlYzctMzk4ZC00YjEzLWI5ODYtODE3NGFlOWEyZGRlIiwidXNlcm5hbWUiOiJQZXJzb25hX1NoaXBfTWlsbGVuaXVtRmFsY29uIiwicm9sZSI6IlNoaXAiLCJhdWQiOiJkZWJsYXNpcy5TcGFjZVRyYWZmaWNDb250cm9sIiwiZXhwIjoxNjMyNDEwMTA2LCJqdGkiOiIxNWM3NDJkOC04NjQ5LTQ2ZjktYWI1OS03NmMyYjBiOGRjOTUiLCJpYXQiOjE2MzIzMjM3MDYsImlzcyI6Imh0dHA6Ly9kZWJsYXNpcy12MS1BdXRoU2VydmljZSJ9.vvp7-7qUDKSNNN7H92ywxE9oa3uabQ3VRf3Yq2OePmTfFf2zdP4ZwXNplPDrWfdEhTLUk559MHJzuoWHK5EOqx0rvOeo_nn5Uq7UWl1bseDbmb_pBvTV6e__aeivpKgXNFmDhYRe4atRdQEJvFERfZfanU7ro-Z8MIW9AwReBFr2tmJ9v4flSFS_DCHia-GdzwkpV0NN3Fr1SmYLAu96ZWDsXNF1ECK8WMD8o144i1Tx0MbdGjKKHvXglPkGS3Bt1S79unt7of7jgAUmwYpSLn_mruuqwUHjRl3abfdBlavKLVzuYaTEe16f0FKHaqMOUrTLLtkqJKz9XNl4oaBUMw

{
   "weight": 124123.52
}

###

//RequestLanding
POST {{baseUrl}}/shipping-station/request-landing HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTJmMDBmNmEtOTU5MS00YWFiLWE4ZjktNzVkYTIzNjExOWQ3IiwidXNlcm5hbWUiOiJQZXJzb25hX1NoaXBfTWlsbGVuaXVtRmFsY29uIiwicm9sZSI6IlNoaXAiLCJhdWQiOiJkZWJsYXNpcy5TcGFjZVRyYWZmaWNDb250cm9sIiwiZXhwIjoxNjMyNzAwMjk1LCJqdGkiOiI4N2ZlNjE1ZC0yNWRjLTQ2NGQtOGUzZC00Y2IyOTI3ZjMwN2YiLCJpYXQiOjE2MzI2MTM4OTUsImlzcyI6Imh0dHA6Ly9kZWJsYXNpcy12MS1BdXRoU2VydmljZSJ9.PyVaEWay--g5u5fk_z3cVgu8R_40gt24XjD0Zmo4uxxDe5oNDfMhoYLNAzCGceYc9ujeJ8Y4Z90KqJxXAsakmMp6a2BykwCGQ_p2GyMVf3L0aVE7tUVNq_V-D2LqGyF9Zei5mfgIeQ_hYzPCNRQgY49sCdd0NVEKP_F4IXM1jZRtc1aOgR6Bl8CXdeuc-m77SfrJga4aC2HbXMV2EdjAKONoljNPVxxZQcSc5WGbDeh7lhxZ8sLMUlEMkUVup1FtrwChV38Ovz8dH5sTVRYjZo44-YJ-OOufCjnhWn7R0YaMZBBEYJS1Twcba27UgvewmbIS6g1d2GXLLGm93LfwuA

{
   "time": 10
}







# grpcurl -import-path ./services/auth_dbsvc/pb/ -proto auth_dbsvc.proto -d @ -plaintext localhost:8082 AuthDBSvc/CreateUser <<EOM                                                                             baremetal-cluster 
# {
#   "user": {
#     "username": "He6a6rl86757r8a4ltto",
#     "password": "Hello",
#     "role": "COMMAND"
#   }
# }
# EOM