@baseUrl = http://localhost:8081

//HEALTH
GET {{baseUrl}}/health HTTP/1.1

###

//CreateUser KO
POST {{baseUrl}}/user/signup HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOGU0YjcwZDMtMWVkNC00NDc4LWExZjYtOWNlYjM2NGFlNzlmIiwidXNlcm5hbWUiOiJQZXJzb25hX1N0YXRpb25fRGVhdGhTdGFyIiwicm9sZSI6IlN0YXRpb24iLCJhdWQiOiJkZWJsYXNpcy5TcGFjZVRyYWZmaWNDb250cm9sIiwiZXhwIjoxNjMyMzc5NTYyLCJqdGkiOiJkMzZhMTdiMS00YWJmLTRlNzQtYjRmYy00MmQ4MTNmMWRlZDciLCJpYXQiOjE2MzIyOTMxNjIsImlzcyI6Imh0dHA6Ly9kZWJsYXNpcy12MS1BdXRoU2VydmljZSJ9.CQCq_-0wy_c5C9BXLWaPq6LXqVIl2vKW-HRPfJP7jh4fR5wbwleuf9G_WDaIj3icg_tbbdyEu6eHd0gNwHenDeIpoSjX6zZbYMLqiufTOppehWCmCy6d3WlL6hkGmCfhMHvTc124sbcKzSF2ajfSd2WuxWDZyA1lEfz2bD3MHWpSpM0BngqlGrvS_zFZfmc5p7SO-o70jDn89XbyGH-wuKTaNc0xN3KizQT4fFgRdj7OZQBYKXQ7LLao5gThRKxb0pzmbR5ZVECDateclHJ21M63x0ve1yGdDf1RN6bZEHcyseU4AvEhly8XBEcXsf_Ks6j0o9Hfj34gvVZv-iX2bQ
Content-Type: application/json; charset=utf-8

{
    "username": "asdasasddaaafvagaasuaw4a",
    "password": "asddaeawea",
    "role": "Ship"
}

###

//Login
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "username": "deblasis",
    "password": "password!"
}

###

//Login
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "username": "Persona_Ship_MilleniumFalcon",
    "password": "Persona_Ship_MilleniumFalcon"
}

###

//RegisterStation
POST {{baseUrl}}/centcom/station/register HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOGU0YjcwZDMtMWVkNC00NDc4LWExZjYtOWNlYjM2NGFlNzlmIiwidXNlcm5hbWUiOiJQZXJzb25hX1N0YXRpb25fRGVhdGhTdGFyIiwicm9sZSI6IlN0YXRpb24iLCJhdWQiOiJkZWJsYXNpcy5TcGFjZVRyYWZmaWNDb250cm9sIiwiZXhwIjoxNjMyMzgzMzIyLCJqdGkiOiJkNjJkODUwMy03YWE4LTQ3YWItOGYyMy00MmRmYzlkMzVhMDUiLCJpYXQiOjE2MzIyOTY5MjIsImlzcyI6Imh0dHA6Ly9kZWJsYXNpcy12MS1BdXRoU2VydmljZSJ9.HWqBP12fyh6edwQXlibhYvhmzhoe_JQJh8a9_unm5txYHbU28zvCXoxhPH7KMc_PK5aajizttCgZ5B1nucswzig6Qo7UhYGOeONxUqH0nizB35b40-LuQTtzoEbwNnNbPxyQZlMPgbfwRr4D_3twEPStWDKZZPmSJs3G6fIextv1wgrXYcW_vcQd4W-PFPVHKMCBjIFZetidqluEKgYVwFR0yqRAtXRuKOXiryZG9HJxxZzIkZs2tA3m8D5wPJdnHK27caZCF6GQlpxtt8TLSOj92--K6xiC5Wp-y2jiE7ld-nbz2wrVYlSJAeMZ0NjToXwheD4uaRqjNJDNZ8GBCA

{
   "capacity":"2342.4234",
   "docks":[
      {
         "numDockingPorts":"15"
      }
   ]
}
###
GET {{baseUrl}}/centcom/station/all HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiM2FmM2M2YWYtNzFlYS00M2ZjLWE4YmEtM2ZiZmJmYTI1OGMyIiwidXNlcm5hbWUiOiJkZWJsYXNpcyIsInJvbGUiOiJDb21tYW5kIiwiYXVkIjoiZGVibGFzaXMuU3BhY2VUcmFmZmljQ29udHJvbCIsImV4cCI6MTYzMjQ3NTkxMiwianRpIjoiY2U2M2Y0YjYtYjQyOC00OTAyLTg4NjktZTRjODEyZDRjZWQzIiwiaWF0IjoxNjMyMzg5NTEyLCJpc3MiOiJodHRwOi8vZGVibGFzaXMtdjEtQXV0aFNlcnZpY2UifQ.BRbtONJFWN5Tb4cmQvGoAGB3cKpXYj85Z0eTGNhw7TTlbGdzkyY2LjLwoLytztoLkMdEb3-5TIVjpV2uaXKPK6L9xFEOKoOFrvwqSRprDSUVnipY8w4RpR6fkcx8NTEdSwcokgcsRac88oOAW5t89IUiu__c9K10vKomUOWMxRbfMbGsy94QYjtTeOsZiDxSJAmISY-abQMUhjeD5SKMCF_bCUmzyZTtgYkM7x0dZ1rS9G99fFpJEhJy0vYcL1fMVFHGK16xJcEJuArYCzDxMa7g3PlB-BgV-Lme7c3BOZX4WSVA6p3bRvo4Ux2G5-GlwnRqJil8SKy3eAS3VFGrRA


###
GET {{baseUrl}}/centcom/ship/all HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTdiZDBlYzctMzk4ZC00YjEzLWI5ODYtODE3NGFlOWEyZGRlIiwidXNlcm5hbWUiOiJQZXJzb25hX1NoaXBfTWlsbGVuaXVtRmFsY29uIiwicm9sZSI6IlNoaXAiLCJhdWQiOiJkZWJsYXNpcy5TcGFjZVRyYWZmaWNDb250cm9sIiwiZXhwIjoxNjMyNDEwMTA2LCJqdGkiOiIxNWM3NDJkOC04NjQ5LTQ2ZjktYWI1OS03NmMyYjBiOGRjOTUiLCJpYXQiOjE2MzIzMjM3MDYsImlzcyI6Imh0dHA6Ly9kZWJsYXNpcy12MS1BdXRoU2VydmljZSJ9.vvp7-7qUDKSNNN7H92ywxE9oa3uabQ3VRf3Yq2OePmTfFf2zdP4ZwXNplPDrWfdEhTLUk559MHJzuoWHK5EOqx0rvOeo_nn5Uq7UWl1bseDbmb_pBvTV6e__aeivpKgXNFmDhYRe4atRdQEJvFERfZfanU7ro-Z8MIW9AwReBFr2tmJ9v4flSFS_DCHia-GdzwkpV0NN3Fr1SmYLAu96ZWDsXNF1ECK8WMD8o144i1Tx0MbdGjKKHvXglPkGS3Bt1S79unt7of7jgAUmwYpSLn_mruuqwUHjRl3abfdBlavKLVzuYaTEe16f0FKHaqMOUrTLLtkqJKz9XNl4oaBUMw

###

//RegisterShip
POST {{baseUrl}}/centcom/ship/register HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTdiZDBlYzctMzk4ZC00YjEzLWI5ODYtODE3NGFlOWEyZGRlIiwidXNlcm5hbWUiOiJQZXJzb25hX1NoaXBfTWlsbGVuaXVtRmFsY29uIiwicm9sZSI6IlNoaXAiLCJhdWQiOiJkZWJsYXNpcy5TcGFjZVRyYWZmaWNDb250cm9sIiwiZXhwIjoxNjMyNDEwMTA2LCJqdGkiOiIxNWM3NDJkOC04NjQ5LTQ2ZjktYWI1OS03NmMyYjBiOGRjOTUiLCJpYXQiOjE2MzIzMjM3MDYsImlzcyI6Imh0dHA6Ly9kZWJsYXNpcy12MS1BdXRoU2VydmljZSJ9.vvp7-7qUDKSNNN7H92ywxE9oa3uabQ3VRf3Yq2OePmTfFf2zdP4ZwXNplPDrWfdEhTLUk559MHJzuoWHK5EOqx0rvOeo_nn5Uq7UWl1bseDbmb_pBvTV6e__aeivpKgXNFmDhYRe4atRdQEJvFERfZfanU7ro-Z8MIW9AwReBFr2tmJ9v4flSFS_DCHia-GdzwkpV0NN3Fr1SmYLAu96ZWDsXNF1ECK8WMD8o144i1Tx0MbdGjKKHvXglPkGS3Bt1S79unt7of7jgAUmwYpSLn_mruuqwUHjRl3abfdBlavKLVzuYaTEe16f0FKHaqMOUrTLLtkqJKz9XNl4oaBUMw

{
   "weight": 124123.52
}


# grpcurl -import-path ./services/auth_dbsvc/pb/ -proto auth_dbsvc.proto -d @ -plaintext localhost:8082 AuthDBSvc/CreateUser <<EOM                                                                             baremetal-cluster 
# {
#   "user": {
#     "username": "He6a6rl86757r8a4ltto",
#     "password": "Hello",
#     "role": "COMMAND"
#   }
# }
# EOM