httpserverport: 9381
grpcserverport: 9382

bindOnLocalhost: true

consul:
  host: consul
  port: 8500
zipkin:
  v2_url: http://zipkin:9411/api/v2/spans

db:
  address: centralcommand_db:5432
  username: postgres
  password: secret
  database: centralcommand
  drivername: postgres
  sslmode: disable

apigateway:
  retrymax: 10
  retrytimeoutms: 5000  

# ssl:
#   serverCert: ../../../../certs/deblasis-stc.pem
#   serverKey: ../../../../certs/deblasis-stc-key.pem


loglevel: debug