httpserverport: 9281
grpcserverport: 9282

bindOnLocalhost: true


serviceName: deblasis-v1-ShippingStation
shortServiceame: shippingstationsvc
namespace: deblasis
tags:
  - ShippingStation
  - deblasis


consul:
  host: consul
  port: 8500
zipkin:
  v2_url: http://zipkin:9411/api/v2/spans


apigateway:
  retrymax: 10
  retrytimeoutms: 5000

db:
  address: localhost:5433
  username: postgres
  password: secret
  database: postgres
  drivername: postgres
  sslmode: disable
jwt:
  privkeypath: /certs/jwt.pem.key
  pubkeypath: /certs/jwt.pem.pub
#one day  
  tokenduration: 86400   

# ssl:
#   serverCert: ../../../../certs/deblasis-stc.pem
#   serverKey: ../../../../certs/deblasis-stc-key.pem


loglevel: debug