httpserverport: 8081
grpcserverport: 8082

db:
  address: authdb.127.0.0.1:5432
  username: postgres
  password: secret
  database: postgres
  sslmode: disable
  drivername: postgres


loglevel: debug