/*
 * [deblasis] Space Traffic Control
 *
 * The [MCRN](https://expanse.fandom.com/wiki/Martian_Congressional_Republic_Navy) wants to build and deploy new software to all their space stations spread throughout the Solar System. With the exponential increase of trade between the [OPA](https://expanse.fandom.com/wiki/Outer_Planets_Alliance) and the [Earth](https://expanse.fandom.com/wiki/Earth) the legacy systems running on Martian space stations have been having difficulty directing and optimizing traffic.
 *
 * API version: 1.0.0
 * Contact: alex@deblasis.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v1/",
		Index,
	},

	Route{
		"Login",
		strings.ToUpper("Post"),
		"/v1/auth/login",
		Login,
	},

	Route{
		"Signup",
		strings.ToUpper("Post"),
		"/v1/user/signup",
		Signup,
	},

	Route{
		"ShipRegister",
		strings.ToUpper("Post"),
		"/v1/centcom/ship/register",
		ShipRegister,
	},

	Route{
		"ShipsList",
		strings.ToUpper("Get"),
		"/v1/centcom/ship/all",
		ShipsList,
	},

	Route{
		"StationRegister",
		strings.ToUpper("Post"),
		"/v1/centcom/station/register",
		StationRegister,
	},

	Route{
		"StationsList",
		strings.ToUpper("Get"),
		"/v1/centcom/station/all",
		StationsList,
	},

	Route{
		"ShipLand",
		strings.ToUpper("Post"),
		"/v1/shipping-station/land",
		ShipLand,
	},

	Route{
		"ShipRequestLanding",
		strings.ToUpper("Post"),
		"/v1/shipping-station/request-landing",
		ShipRequestLanding,
	},
}
