name: E2E Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Env setup
        run: export GO111MODULE=on  
      - name: Build the stack
        run: make integration-tests-env
      - name: E2E Tests
        run: docker-compose run integrationtester