#
# Copyright 2021 Alessandro De Blasis <alex@deblasis.net>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: E2E Tests
on: push
jobs:
  run_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'  
      - name: Build and Run the stack
        run: DOCKERCOMPOSE="docker-compose" COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 make integrationtests-up
      - name: Seed initial data
        run: make seed-auth_dbsvc
      - name: Check status
        run: sleep 15 && docker ps
      - name: Run E2E Tests
        run: DOCKERCOMPOSE="docker-compose" make integrationtests-run
