name: E2E Tests
on: push
jobs:
  run_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'  
      - name: Build, run, seed, e2e test
        run: |
          DOCKERCOMPOSE="docker-compose" COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 make integrationtests-up \
          && @echo "\n\nSEED INITIAL USER\n\n" \
          && make seed-auth_dbsvc \
          && @echo "\n\nE2E TESTS\n\n" \
          DOCKERCOMPOSE="docker-compose" make integrationtests-run
# - name: Seed initial user
#   run: make seed-auth_dbsvc
# - name: E2E Tests
#   run: DOCKERCOMPOSE="docker-compose" make integrationtests-run