name: E2E Tests
on: push
jobs:
  run_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'  
      - name: Build the stack
        run: DOCKERCOMPOSE="docker-compose" make integration-tests-env
      - name: E2E Tests
        run: docker-compose run integrationtester